import { ApiProperty } from '@nestjs/swagger';

export class CreateNanoregDto {
  @ApiProperty({ example: 'string' }) Name: string;
  @ApiProperty({ example: 'string' }) Company: string;
  @ApiProperty({ example: '2025-08-14', type: String, format: 'date' }) RegisterDate: Date;
  @ApiProperty({ example: 'string' }) MobileNo: string;
  @ApiProperty({ example: 'string' }) State: string;
  @ApiProperty({ example: 'string' }) Address: string;
  @ApiProperty({ example: 'string' }) Email: string;
  @ApiProperty({ example: 'Y' }) Active: string;
  @ApiProperty({ example: 'Y' }) IsPaid: string;
  @ApiProperty({ example: 'string' }) HDID: string;
  @ApiProperty({ example: 'string' }) PaymentDet: string;
  @ApiProperty({ example: 'string' }) ActivatedOn: string;
  @ApiProperty({ example: 'string', required: false }) SerialNo?: string;
  @ApiProperty({ example: 'string' }) Area: string;
  @ApiProperty({ example: 'string' }) Pincode: string;
  @ApiProperty({ example: 'string' }) PayMode: string;
  @ApiProperty({ example: 'string' }) BankName: string;
  @ApiProperty({ example: 'string' }) BankAccNo: string;
  @ApiProperty({ example: 'string' }) AccName: string;
  @ApiProperty({ example: 1 }) PaidAmt: number;
  @ApiProperty({ example: '2025-08-14', type: String, format: 'date' }) ValidUpTo: Date;
  @ApiProperty({ example: '2025-08-14', type: String, format: 'date' }) ReceiptDate: Date;
  @ApiProperty({ example: 0 }) AlterBy: number;
  @ApiProperty({ example: '2025-08-14', type: String, format: 'date' }) AlteredOn: Date;
  @ApiProperty({ example: 0 }) InvNo: number;
  @ApiProperty({ example: '2025-08-14', type: String, format: 'date' }) InvDate: Date;
  @ApiProperty({ example: 'Y' }) IsSurrendered: string;
  @ApiProperty({ example: 1 }) DueAmt: number;
  @ApiProperty({ example: 'string', required: false }) GSTIN?: string;
  @ApiProperty({ example: 'string', required: false }) Partner?: string;
  @ApiProperty({ example: 'string', required: false }) TallySerial?: string;
  @ApiProperty({ example: 'Y', required: false }) IsMultiUser?: string;
  @ApiProperty({ example: 'Y' }) IsServer: string;
  @ApiProperty({ example: 0 }) IsAPIClient: number;
  @ApiProperty({ example: 'Y' }) IsLocalSales: string;
  @ApiProperty({ example: 10.10, required: false }) AssValue?: number;
  @ApiProperty({ example: 10.10, required: false }) IGST?: number;
  @ApiProperty({ example: 10.10, required: false }) CGST?: number;
  @ApiProperty({ example: 10.10, required: false }) SGST?: number;
  @ApiProperty({ example: 100.10, required: false }) Roundoff?: number;
  @ApiProperty({ example: 'Y', required: false }) Prefix?: string;
  @ApiProperty({ example: 2.3 }) Version: number;
  @ApiProperty({ example: 'string' }) SystemName: string;
  @ApiProperty({ example: 2.3 }) RunningVersion: number;
  @ApiProperty({ example: 2, required: false }) license_no?: number;
  @ApiProperty({ example: 'Y' }) IsAccountsfirst: string;
  @ApiProperty({ example: 'Y', required: false }) IsFinancialStatement?: string;
}
