import { ApiProperty } from '@nestjs/swagger';

export class CreateNanoregDto {
  @ApiProperty({ example: 'string', required: false }) Name?: string;
  @ApiProperty({ example: 'string', required: false }) Company?: string;
  @ApiProperty({ example: '2025-08-14', type: String, format: 'date', required: false }) RegisterDate?: Date;
  @ApiProperty({ example: 'string', required: false }) MobileNo?: string;
  @ApiProperty({ example: 'string', required: false }) State?: string;
  @ApiProperty({ example: 'string', required: false }) Address?: string;
  @ApiProperty({ example: 'string', required: false }) Email?: string;
  @ApiProperty({ example: 'Y', required: false }) Active?: string;
  @ApiProperty({ example: 'Y', required: false }) IsPaid?: string;
  @ApiProperty({ example: 'string', required: false }) HDID?: string;
  @ApiProperty({ example: 'string', required: false }) PaymentDet?: string;
  @ApiProperty({ example: 'string', required: false }) ActivatedOn?: string;
  @ApiProperty({ example: 'string', required: false }) SerialNo?: string;
  @ApiProperty({ example: 'string', required: false }) Area?: string;
  @ApiProperty({ example: 'string', required: false }) Pincode?: string;
  @ApiProperty({ example: 'string', required: false }) PayMode?: string;
  @ApiProperty({ example: 'string', required: false }) BankName?: string;
  @ApiProperty({ example: 'string', required: false }) BankAccNo?: string;
  @ApiProperty({ example: 'string', required: false }) AccName?: string;
  @ApiProperty({ example: 1, required: false }) PaidAmt?: number;
  @ApiProperty({ example: '2025-08-14', type: String, format: 'date', required: false }) ValidUpTo?: Date;
  @ApiProperty({ example: '2025-08-14', type: String, format: 'date', required: false }) ReceiptDate?: Date;
  @ApiProperty({ example: 0, required: false }) AlterBy?: number;
  @ApiProperty({ example: '2025-08-14', type: String, format: 'date', required: false }) AlteredOn?: Date;
  @ApiProperty({ example: 0, required: false }) InvNo?: number;
  @ApiProperty({ example: '2025-08-14', type: String, format: 'date', required: false }) InvDate?: Date;
  @ApiProperty({ example: 'Y', required: false }) IsSurrendered?: string;
  @ApiProperty({ example: 1, required: false }) DueAmt?: number;
  @ApiProperty({ example: 'string', required: false }) GSTIN?: string;
  @ApiProperty({ example: 'string', required: false }) Partner?: string;
  @ApiProperty({ example: 'string', required: false }) TallySerial?: string;
  @ApiProperty({ example: 'Y', required: false }) IsMultiUser?: string;
  @ApiProperty({ example: 'Y', required: false }) IsServer?: string;
  @ApiProperty({ example: 0, required: false }) IsAPIClient?: number;
  @ApiProperty({ example: 'Y', required: false }) IsLocalSales?: string;
  @ApiProperty({ example: 10.10, required: false }) AssValue?: number;
  @ApiProperty({ example: 10.10, required: false }) IGST?: number;
  @ApiProperty({ example: 10.10, required: false }) CGST?: number;
  @ApiProperty({ example: 10.10, required: false }) SGST?: number;
  @ApiProperty({ example: 100.10, required: false }) Roundoff?: number;
  @ApiProperty({ example: 'Y', required: false }) Prefix?: string;
  @ApiProperty({ example: 2.3, required: false }) Version?: number;
  @ApiProperty({ example: 'string', required: false }) SystemName?: string;
  @ApiProperty({ example: 2.3, required: false }) RunningVersion?: number;
  @ApiProperty({ example: 2, required: false }) license_no?: number;
  @ApiProperty({ example: 'Y', required: false }) IsAccountsfirst?: string;
  @ApiProperty({ example: 'Y', required: false }) IsFinancialStatement?: string;
}
