import { ApiProperty } from '@nestjs/swagger';

export class CreateNanoregDto {
  @ApiProperty() Name: string;
  @ApiProperty() Company: string;
  @ApiProperty({ type: String, format: 'date-time' }) RegisterDate: Date;
  @ApiProperty() MobileNo: string;
  @ApiProperty() State: string;
  @ApiProperty() Address: string;
  @ApiProperty() Email: string;
  @ApiProperty() Active: string;
  @ApiProperty() IsPaid: string;
  @ApiProperty() HDID: string;
  @ApiProperty() PaymentDet: string;
  @ApiProperty() ActivatedOn: string;
  @ApiProperty({ required: false, nullable: true }) SerialNo?: string;
  @ApiProperty() Area: string;
  @ApiProperty() Pincode: string;
  @ApiProperty() PayMode: string;
  @ApiProperty() BankName: string;
  @ApiProperty() BankAccNo: string;
  @ApiProperty() AccName: string;
  @ApiProperty() PaidAmt: string;
  @ApiProperty({ type: String, format: 'date-time' }) ValidUpTo: Date;
  @ApiProperty({ type: String, format: 'date-time' }) ReceiptDate: Date;
  @ApiProperty() AlterBy: number;
  @ApiProperty({ type: String, format: 'date-time' }) AlteredOn: Date;
  @ApiProperty() InvNo: number;
  @ApiProperty({ type: String, format: 'date-time' }) InvDate: Date;
  @ApiProperty() IsSurrendered: string;
  @ApiProperty() DueAmt: string;
  @ApiProperty({ required: false }) GSTIN?: string;
  @ApiProperty({ required: false }) Partner?: string;
  @ApiProperty({ required: false }) TallySerial?: string;
  @ApiProperty({ required: false }) IsMultiUser?: string;
  @ApiProperty() IsServer: string;
  @ApiProperty() IsAPIClient: number;
  @ApiProperty() IsLocalSales: string;
  @ApiProperty({ required: false }) AssValue?: string;
  @ApiProperty({ required: false }) IGST?: string;
  @ApiProperty({ required: false }) CGST?: string;
  @ApiProperty({ required: false }) SGST?: string;
  @ApiProperty({ required: false }) Roundoff?: string;
  @ApiProperty({ required: false }) Prefix?: string;
  @ApiProperty() Version: string;
  @ApiProperty() SystemName: string;
  @ApiProperty() RunningVersion: string;
  @ApiProperty({ required: false }) license_no?: string;
  @ApiProperty() IsAccountsfirst: string;
  @ApiProperty({ required: false }) IsFinancialStatement?: string;
}
